# Generated by Django 5.2.4 on 2025-08-13 10:13

import weathers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteopointprovider',
            name='status',
            field=models.JSONField(blank=True, default=weathers.models.default_meteo_point_provider_status, verbose_name='Статус'),
        ),
    ]
